-- :disable-transaction
alter table "public"."access" add constraint "pk_access_id" primary key ("id");
--;;
alter table "public"."access" add constraint "uq_access_name" unique ("name");
--;;
alter table "public"."contact" add constraint "pk_contact_id" primary key ("id");
--;;
alter table "public"."country" add constraint "pk_country_id" primary key ("id");
--;;
alter table "public"."country" add constraint "uq_country_name" unique ("name");
--;;
alter table "public"."language" add constraint "pk_language_code" primary key ("code");
--;;
alter table "public"."language" add constraint "uq_language_name" unique ("name");
--;;
alter table "public"."language" add constraint "uq_language_eng_name" unique ("eng_name");
--;;
alter table "public"."industry" add constraint "pk_industry_id" primary key ("id");
--;;
alter table "public"."industry" add constraint "uq_industry_name" unique ("name");
--;;
alter table "public"."affiliate" add constraint "pk_affiliate_id" primary key ("id");
--;;
alter table "public"."affiliate" add constraint "uq_affiliate_code" unique ("code");
--;;
alter table "public"."affiliate" add constraint "uq_affiliate_reg_no" unique ("reg_no");
--;;
alter table "public"."affiliate" add constraint "uq_affiliate_tax_no" unique ("tax_no");
--;;
alter table "public"."affiliate" add constraint "fk_affiliate_lang" foreign key ("lang") references "public"."language" ("code") match full;
--;;
alter table "public"."aff_doc" add constraint "pk_aff_doc_id" primary key ("id");
--;;
alter table "public"."aff_doc" add constraint "fk_aff_doc_aff_id" foreign key ("aff_id") references "public"."affiliate" ("id") match full;
--;;
alter table "public"."currency" add constraint "pk_currency_id" primary key ("id");
--;;
alter table "public"."currency" add constraint "uq_currency_name" unique ("name");
--;;
alter table "public"."bank_acc" add constraint "pk_bank_acc_id" primary key ("id");
--;;
alter table "public"."bank_acc" add constraint "uq_bank_acc_swift_code" unique ("swift_code");
--;;
alter table "public"."bank_acc" add constraint "uq_bank_acc_bank_acc_no" unique ("bank", "acc_no");
--;;
alter table "public"."bank_acc" add constraint "fk_bank_acc_currency_id" foreign key ("currency_id") references "public"."currency" ("id") match full;
--;;
alter table "public"."aff_doc" add constraint "fk_bank_acc_aff_id" foreign key ("aff_id") references "public"."affiliate" ("id") match full;
--;;
alter table "public"."location" add constraint "pk_location_id" primary key ("id");
--;;
alter table "public"."location" add constraint "fk_location_country_id" foreign key ("country_id") references "public"."country" ("id") match full;
--;;
alter table "public"."location" add constraint "fk_location_aff_id" foreign key ("aff_id") references "public"."affiliate" ("id") match full;
--;;
alter table "public"."loc_contact" add constraint "pk_loc_contact_loc_id_contact_id" primary key ("loc_id", "contact_id");
--;;
alter table "public"."loc_contact" add constraint "fk_loc_contact_loc_id" foreign key ("loc_id") references "public"."location" ("id") match full;
--;;
alter table "public"."loc_contact" add constraint "fk_loc_contact_contact_id" foreign key ("contact_id") references "public"."contact" ("id") match full;
--;;
alter table "public"."module" add constraint "pk_module_id" primary key ("id");
--;;
alter table "public"."module" add constraint "fk_module_parent_id" foreign key ("parent_id") references "public"."module" ("id") match full;
--;;
alter table "public"."module" add constraint "fk_module_access_name" foreign key ("access") references "public"."access" ("name") match full;
--;;
alter table "public"."user" add constraint "pk_user_id" primary key ("id");
--;;
alter table "public"."user" add constraint "fk_user_aff_id" foreign key ("aff_id") references "public"."affiliate" ("id") match full;
--;;
alter table "public"."user" add constraint "fk_user_lang" foreign key ("lang") references "public"."language" ("code") match full;
--;;
alter table "public"."user" add constraint "uq_user_username" unique ("username");
--;;
alter table "public"."user" add constraint "uq_user_email" unique ("email");
--;;
alter table "public"."user_contact" add constraint "pk_user_contact_user_id_contact_id" primary key ("user_id", "contact_id");
--;;
alter table "public"."user_contact" add constraint "fk_user_contact_user_id" foreign key ("user_id") references "public"."user" ("id") match full;
--;;
alter table "public"."user_contact" add constraint "fk_user_contact_contact_id" foreign key ("contact_id") references "public"."contact" ("id") match full;
--;;
alter table "public"."announcement" add constraint "pk_announcement_id" primary key ("id");
--;;
alter table "public"."announce_aff" add constraint "fk_announce_aff_aff_id" foreign key ("aff_id") references "public"."affiliate" ("id") match full;
--;;
alter table "public"."announce_aff" add constraint "fk_announce_aff_ann_id" foreign key ("ann_id") references "public"."announcement" ("id") match full;
--;;
alter table "public"."password_policy" add constraint "pk_password_policy_id" primary key ("id");
--;;
alter table "public"."password_policy" add constraint "fk_password_policy_aff_id" foreign key ("aff_id") references "public"."affiliate" ("id") match full;
--;;
alter table "public"."password_policy" add constraint "uq_password_policy_aff_id" unique ("aff_id");
--;;
alter table "public"."audit_log" add constraint "pk_audit_log_id" primary key ("id");
--;;
alter table "public"."role" add constraint "pk_role_id" primary key ("id");
--;;
alter table "public"."role" add constraint "fk_role_aff_id" foreign key ("aff_id") references "public"."affiliate" ("id") match full;
--;;
alter table "public"."role" add constraint "uq_aff_id_role_name" unique ("aff_id", "name");
--;;
alter table "public"."role_access" add constraint "fk_role_role_id" foreign key ("role_id") references "public"."role" ("id") match full;
--;;
alter table "public"."role_access" add constraint "fk_role_access_id" foreign key ("access_id") references "public"."access" ("id") match full;
--;;
alter table "public"."user_role" add constraint "fk_user_role_user_id" foreign key ("user_id") references "public"."user" ("id") match full;
--;;
alter table "public"."user_role" add constraint "fk_user_role_role_id" foreign key ("role_id") references "public"."role" ("id") match full;
--;;
alter table "public"."party" add constraint "pk_party_id" primary key ("id");
--;;
alter table "public"."party" add constraint "fk_party_country" foreign key ("country_id") references "public"."country" ("id") match full;
--;;
alter table "public"."category" add constraint "pk_category_id" primary key ("id");
--;;
alter table "public"."sub_category" add constraint "pk_sub_cat_id" primary key ("id");
--;;
alter table "public"."category" add constraint "uq_cat_name" unique ("name");
--;;
alter table "public"."sub_category" add constraint "uq_sub_cat_id_name" unique ("cat_id", "name");
--;;
alter table "public"."quotation" add constraint "pk_quote_id" primary key ("id");
--;;
alter table "public"."quotation" add constraint "uq_quote_quote_no" unique ("quote_no");
--;;
alter table "public"."quotation" add constraint "fk_quote_issued_to" foreign key ("issued_to") references "public"."party" ("id") match full;
--;;
alter table "public"."quotation" add constraint "fk_quote_issued_by" foreign key ("issued_by") references "public"."party" ("id") match full;
--;;
alter table "public"."quotation" add constraint "fk_quote_cat_id" foreign key ("cat_id") references "public"."category" ("id") match full;
--;;
alter table "public"."quotation" add constraint "fk_quote_sub_cat_id" foreign key ("sub_cat_id") references "public"."sub_category" ("id") match full;
--;;
alter table "public"."quote_item" add constraint "pk_quote_item_id" primary key ("id");
--;;
alter table "public"."quote_item" add constraint "fk_quote_item_quote_id" foreign key ("quote_id") references "public"."quotation" ("id") match full;
--;;
alter table "public"."quote_misc" add constraint "pk_quote_misc_id" primary key ("id");
--;;
alter table "public"."quote_misc" add constraint "fk_quote_misc_quote_id" foreign key ("quote_id") references "public"."quotation" ("id") match full;
--;;
alter table "public"."quote_discount" add constraint "pk_quote_discount_id" primary key ("id");
--;;
alter table "public"."quote_discount" add constraint "fk_quote_discount_quote_id" foreign key ("quote_id") references "public"."quotation" ("id") match full;
--;;
alter table "public"."invoice" add constraint "pk_invoice_id" primary key ("id");
--;;
alter table "public"."invoice" add constraint "uq_inv_inv_no" unique ("inv_no");
--;;
alter table "public"."invoice" add constraint "fk_inv_issued_to" foreign key ("issued_to") references "public"."party" ("id") match full;
--;;
alter table "public"."invoice" add constraint "fk_inv_issued_by" foreign key ("issued_by") references "public"."party" ("id") match full;
--;;
alter table "public"."invoice" add constraint "fk_inv_cat_id" foreign key ("cat_id") references "public"."category" ("id") match full;
--;;
alter table "public"."invoice" add constraint "fk_inv_sub_cat_id" foreign key ("sub_cat_id") references "public"."sub_category" ("id") match full;
--;;
alter table "public"."invoice_item" add constraint "pk_inv_item_id" primary key ("id");
--;;
alter table "public"."invoice_item" add constraint "fk_inv_item_inv_id" foreign key ("inv_id") references "public"."invoice" ("id") match full;
--;;
alter table "public"."invoice_misc" add constraint "pk_inv_misc_id" primary key ("id");
--;;
alter table "public"."invoice_misc" add constraint "fk_inv_misc_inv_id" foreign key ("inv_id") references "public"."invoice" ("id") match full;
--;;
alter table "public"."invoice_discount" add constraint "pk_inv_discount_id" primary key ("id");
--;;
alter table "public"."invoice_discount" add constraint "fk_inv_discount_inv_id" foreign key ("inv_id") references "public"."invoice" ("id") match full;
--;;
alter table "public"."quote_inv_ref" add constraint "fk_quote_inv_quote" foreign key ("quote_id") references "public"."quotation" ("id") match full;
--;;
alter table "public"."quote_inv_ref" add constraint "fk_quote_inv_inv" foreign key ("inv_id") references "public"."invoice" ("id") match full;
--;;
alter table "public"."quote_inv_ref" add constraint "uq_quote_inv_inv" unique ("inv_id");
--;;
alter table "public"."work_order" add constraint "pk_wo_id" primary key ("id");
--;;
alter table "public"."work_order" add constraint "uq_wo_wo_no" unique ("wo_no");
--;;
alter table "public"."work_order" add constraint "fk_wo_issued_to" foreign key ("issued_to") references "public"."party" ("id") match full;
--;;
alter table "public"."work_order" add constraint "fk_wo_issued_by" foreign key ("issued_by") references "public"."party" ("id") match full;
--;;
alter table "public"."work_order" add constraint "fk_wo_cat_id" foreign key ("cat_id") references "public"."category" ("id") match full;
--;;
alter table "public"."work_order" add constraint "fk_wo_sub_cat_id" foreign key ("sub_cat_id") references "public"."sub_category" ("id") match full;
--;;
alter table "public"."wo_item" add constraint "pk_wo_item_id" primary key ("id");
--;;
alter table "public"."wo_item" add constraint "fk_wo_item_wo_id" foreign key ("wo_id") references "public"."work_order" ("id") match full;
--;;
alter table "public"."wo_misc" add constraint "pk_wo_misc_id" primary key ("id");
--;;
alter table "public"."wo_misc" add constraint "fk_wo_misc_wo_id" foreign key ("wo_id") references "public"."work_order" ("id") match full;
--;;
alter table "public"."wo_discount" add constraint "pk_wo_discount_id" primary key ("id");
--;;
alter table "public"."wo_discount" add constraint "fk_wo_discount_wo_id" foreign key ("wo_id") references "public"."work_order" ("id") match full;
--;;
alter table "public"."quote_wo_ref" add constraint "fk_quote_wo_quote" foreign key ("quote_id") references "public"."quotation" ("id") match full;
--;;
alter table "public"."quote_wo_ref" add constraint "fk_quote_wo_wo" foreign key ("wo_id") references "public"."work_order" ("id") match full;
--;;
alter table "public"."quote_wo_ref" add constraint "uq_quote_wo_wo" unique ("wo_id");
--;;
alter table "public"."wo_inv_ref" add constraint "fk_wo_inv_wo" foreign key ("wo_id") references "public"."work_order" ("id") match full;
--;;
alter table "public"."wo_inv_ref" add constraint "fk_wo_inv_inv" foreign key ("inv_id") references "public"."invoice" ("id") match full;
--;;
alter table "public"."wo_inv_ref" add constraint "uq_wo_inv_inv" unique ("inv_id");
