-- :disable-transaction
drop table if exists "public"."guestbook" cascade;
--;;
drop table if exists "public"."access" cascade;
--;;
drop table if exists "public"."affiliate" cascade;
--;;
drop table if exists "public"."aff_doc" cascade;
--;;
drop table if exists "public"."bank_acc" cascade;
--;;
drop table if exists "public"."contact" cascade;
--;;
drop table if exists "public"."country" cascade;
--;;
drop table if exists "public"."currency" cascade;
--;;
drop table if exists "public"."industry" cascade;
--;;
drop table if exists "public"."language" cascade;
--;;
drop table if exists "public"."location" cascade;
--;;
drop table if exists "public"."loc_contact" cascade;
--;;
drop table if exists "public"."module" cascade;
--;;
drop table if exists "public"."registration" cascade;
--;;
drop sequence if exists "public"."seq_registration" cascade;
--;;
drop table if exists "public"."user" cascade;
--;;
drop table if exists "public"."user_contact" cascade;
--;;
drop table if exists "public"."password_history" cascade;
--;;
drop table if exists "public"."announcement" cascade;
--;;
drop table if exists "public"."announce_aff" cascade;
--;;
drop table if exists "public"."password_policy" cascade;
--;;
drop sequence if exists "public"."seq_pwd_policy" cascade;
--;;
drop table if exists "public"."audit_log" cascade;
--;;
drop table if exists "public"."user" cascade;
