-- :disable-transaction
drop table if exists "public"."guestbook" cascade;
--;;
drop table if exists "public"."access" cascade;
--;;
drop table if exists "public"."aff_doc" cascade;
--;;
drop table if exists "public"."affiliate" cascade;
--;;
drop table if exists "public"."announce_aff" cascade;
--;;
drop table if exists "public"."announcement" cascade;
--;;
drop table if exists "public"."audit_log" cascade;
--;;
drop table if exists "public"."bank_acc" cascade;
--;;
drop table if exists "public"."contact" cascade;
--;;
drop table if exists "public"."country" cascade;
--;;
drop table if exists "public"."currency" cascade;
--;;
drop table if exists "public"."industry" cascade;
--;;
drop table if exists "public"."language" cascade;
--;;
drop table if exists "public"."loc_contact" cascade;
--;;
drop table if exists "public"."location" cascade;
--;;
drop table if exists "public"."module" cascade;
--;;
drop table if exists "public"."password_history" cascade;
--;;
drop table if exists "public"."password_policy" cascade;
--;;
drop table if exists "public"."registration" cascade;
--;;
drop table if exists "public"."role" cascade;
--;;
drop table if exists "public"."role_access" cascade;
--;;
drop sequence if exists "public"."seq_pwd_policy" cascade;
--;;
drop sequence if exists "public"."seq_registration" cascade;
--;;
drop table if exists "public"."user" cascade;
--;;
drop table if exists "public"."user_contact" cascade;
--;;
drop table if exists "public"."user_role" cascade;
--;;
drop table if exists "public"."party" cascade;
--;;
drop table if exists "public"."category" cascade;
--;;
drop table if exists "public"."sub_category" cascade;
--;;
drop table if exists "public"."quotation" cascade;
--;;
drop table if exists "public"."quote_item" cascade;
--;;
drop table if exists "public"."quote_misc" cascade;
--;;
drop table if exists "public"."quote_discount" cascade;
--;;
drop sequence if exists "public"."seq_category" cascade;
--;;
drop sequence if exists "public"."seq_sub_category" cascade;
--;;
drop table if exists "public"."invoice" cascade;
--;;
drop table if exists "public"."invoice_item" cascade;
--;;
drop table if exists "public"."invoice_misc" cascade;
--;;
drop table if exists "public"."invoice_discount" cascade;
--;;
drop table if exists "public"."work_order" cascade;
--;;
drop table if exists "public"."wo_item" cascade;
--;;
drop table if exists "public"."wo_misc" cascade;
--;;
drop table if exists "public"."wo_discount" cascade;
--;;
drop table if exists "public"."quote_inv_ref" cascade;
--;;
drop table if exists "public"."quote_wo_ref" cascade;
--;;
drop table if exists "public"."wo_inv_ref" cascade;
