-- :disable-transaction
alter table "public"."contact" add constraint "pk_contact_id" primary key ("id");
--;;
alter table "public"."country" add constraint "pk_country_id" primary key ("id");
--;;
alter table "public"."country" add constraint "uq_country_name" unique ("name");
--;;
alter table "public"."language" add constraint "pk_language_id" primary key ("id");
--;;
alter table "public"."language" add constraint "uq_language_code" unique ("code");
--;;
alter table "public"."language" add constraint "uq_language_name" unique ("name");
--;;
alter table "public"."language" add constraint "uq_language_eng_name" unique ("eng_name");
--;;
alter table "public"."industry" add constraint "pk_industry_id" primary key ("id");
--;;
alter table "public"."industry" add constraint "uq_industry_name" unique ("name");
--;;
alter table "public"."affiliate" add constraint "pk_affiliate_id" primary key ("id");
--;;
alter table "public"."affiliate" add constraint "uq_affiliate_code" unique ("code");
--;;
alter table "public"."affiliate" add constraint "uq_affiliate_reg_no" unique ("reg_no");
--;;
alter table "public"."affiliate" add constraint "uq_affiliate_tax_no" unique ("tax_no");
--;;
alter table "public"."affiliate" add constraint "fk_affiliate_lang_id" foreign key ("lang_id") references "public"."language" ("id") match full;
--;;
alter table "public"."aff_doc" add constraint "pk_aff_doc_id" primary key ("id");
--;;
alter table "public"."aff_doc" add constraint "fk_aff_doc_aff_id" foreign key ("aff_id") references "public"."affiliate" ("id") match full;
--;;
alter table "public"."currency" add constraint "pk_currency_id" primary key ("id");
--;;
alter table "public"."currency" add constraint "uq_currency_name" unique ("name");
--;;
alter table "public"."bank_acc" add constraint "pk_bank_acc_id" primary key ("id");
--;;
alter table "public"."bank_acc" add constraint "uq_bank_acc_swift_code" unique ("swift_code");
--;;
alter table "public"."bank_acc" add constraint "uq_bank_acc_bank_acc_no" unique ("bank", "acc_no");
--;;
alter table "public"."bank_acc" add constraint "fk_bank_acc_currency_id" foreign key ("currency_id") references "public"."currency" ("id") match full;
--;;
alter table "public"."aff_doc" add constraint "fk_bank_acc_aff_id" foreign key ("aff_id") references "public"."affiliate" ("id") match full;
--;;
alter table "public"."location" add constraint "pk_location_id" primary key ("id");
--;;
alter table "public"."location" add constraint "fk_location_country_id" foreign key ("country_id") references "public"."country" ("id") match full;
--;;
alter table "public"."location" add constraint "fk_location_aff_id" foreign key ("aff_id") references "public"."affiliate" ("id") match full;
--;;
alter table "public"."loc_contact" add constraint "pk_loc_contact_loc_id_contact_id" primary key ("loc_id", "contact_id");
--;;
alter table "public"."loc_contact" add constraint "fk_loc_contact_loc_id" foreign key ("loc_id") references "public"."location" ("id") match full;
--;;
alter table "public"."loc_contact" add constraint "fk_loc_contact_contact_id" foreign key ("contact_id") references "public"."contact" ("id") match full;
--;;
alter table "public"."module" add constraint "pk_module_id" primary key ("id");
--;;
alter table "public"."module" add constraint "fk_module_parent_id" foreign key ("parent_id") references "public"."module" ("id") match full;
--;;
alter table "public"."user" add constraint "pk_user_id" primary key ("id");
--;;
alter table "public"."user" add constraint "fk_user_aff_id" foreign key ("aff_id") references "public"."affiliate" ("id") match full;
--;;
alter table "public"."user" add constraint "fk_user_lang_id" foreign key ("lang_id") references "public"."language" ("id") match full;
--;;
alter table "public"."user" add constraint "uq_user_username" unique ("username");
--;;
alter table "public"."user" add constraint "uq_user_email" unique ("email");
--;;
alter table "public"."user_contact" add constraint "pk_user_contact_user_id_contact_id" primary key ("user_id", "contact_id");
--;;
alter table "public"."user_contact" add constraint "fk_user_contact_user_id" foreign key ("user_id") references "public"."user" ("id") match full;
--;;
alter table "public"."user_contact" add constraint "fk_user_contact_contact_id" foreign key ("contact_id") references "public"."contact" ("id") match full;
--;;
alter table "public"."announcement" add constraint "pk_announcement_id" primary key ("id");
--;;
alter table "public"."announce_aff" add constraint "fk_announce_aff_aff_id" foreign key ("aff_id") references "public"."affiliate" ("id") match full;
--;;
alter table "public"."announce_aff" add constraint "fk_announce_aff_ann_id" foreign key ("ann_id") references "public"."announcement" ("id") match full;
--;;
alter table "public"."password_policy" add constraint "pk_password_policy_id" primary key ("id");
--;;
alter table "public"."password_policy" add constraint "fk_password_policy_aff_id" foreign key ("aff_id") references "public"."affiliate" ("id") match full;
--;;
alter table "public"."password_policy" add constraint "uq_password_policy_aff_id" unique ("aff_id");
--;;
alter table "public"."audit_log" add constraint "pk_audit_log_id" primary key ("id");
